### ISSUE TITLE
Update menu navigation for Kavoon

### ISSUE THREAD

**Issue by yuramax** [boarlabsxyz/Kavoon#136]
This task is a parent task and supposes to combine all child tasks:
- [ ] [Header updates: update the behavior of the main navigation in the header](https://github.com/boarlabsxyz/Kavoon/issues/31)
- [ ] [Header updates: make the shopping cart global - move to the header](https://github.com/boarlabsxyz/Kavoon/issues/30)
- [ ] [Remove unused components based on new location of navigation and cart icon](https://github.com/boarlabsxyz/Kavoon/issues/135)
